fos_rest:
  param_fetcher_listener: true
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }
  view:
    view_response_listener: 'force'
  exception:
    enabled: true
    messages:
      Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true
      Symfony\Component\Security\Core\Exception\AuthenticationException: true
      Symfony\Component\HttpKernel\Exception\ConflictHttpException: true
      Symfony\Component\HttpKernel\Exception\HttpException: true
      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
      \LogicException: 400
      \DomainException: 400
      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 401
      Symfony\Component\Security\Core\Exception\AuthenticationException: 401
      Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
  access_denied_listener:
    enabled: true
    json: true


